events {}

http {
    log_format json_analytics escape=json
      '{"timestamp":"$time_iso8601",'
      '"client_ip":"$remote_addr",'
      '"request":"$request",'
      '"status": $status,'
      '"request_time": $request_time}';

    access_log /var/log/shared/access.json json_analytics;

    server {
        listen 80;

        location / {
            proxy_pass http://api:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}